### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by natlibfi-jonollil** [ryvdx/sveltekit-keycloak-multitenant-example#1]
I tried to do installation based on your docs, but fails on first step.

1. I'm not yarn user so i don't know even basic tricks
2. I tried command in docs:
 ``` 
yarn install -S sveltkit-keycloak-multitenant
yarn install v1.22.19
error `install` has been replaced with `add` to add new dependencies. Run "yarn add sveltkit-keycloak-multitenant" instead.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
3. Do i need some kind base project where to install this? (I tried npm svelte-kit base project `npm create svelte@latest` whit failure)

**Comment by ryvdx** [comment]
Hi, you can use either yarn and npm are for the most part interchangeable package managers.  I use yarn because it addressed docker build issues tied to arm64 and Mac.

Yes, you can also build a new project using "npm create svelte@latest {yourapp}" to get started.  You can look at /demoapp in this example project to see how to add the routes and integrate the library.
